import pytest
from ferret.main import Ferret


def _get_contents_of(file_path):
    try:
        with open(file_path, errors='ignore') as file:
            return file.read()
    except IOError:
        return ''


@pytest.mark.parametrize("website", [
    # "espaco-vital",Ignored due to processing problems

    "aba",
    "abdc",
    "age-mg",
    "agencia-brasil",
    "agu",
    "ajufe",
    "ajufergs",
    "al-ac",
    "al-ce",
    "al-go",
    "al-ms",
    "al-mt",
    "al-pb",
    "al-rj",
    "al-rs",
    "al-sp",
    "al-to",
    "amab",
    "amatra-05",
    "ambito-juridico",
    "anamatra",
    "apbc",
    "apeminas",
    "cd",
    "cgu",
    "cnj",
    "cnmp",
    "conamp",
    "consultor-juridico",
    "controle-publico",
    "correio-forense",
    "correio_da_bahia",
    "dp-al",
    "dp-df",
    "dp-mg",
    "dp-mt",
    "dp-rj",
    "dp-rs",
    "dp-to",
    "dpu",
    "folhapolitica",
    "g1",
    "ibdfam",
    "ibdp-direito-previdenciario",
    "inst-rui-barbosa",
    "internet-legal",
    "jf",
    "jf-al",
    "jornal-ordem-rs",
    "juristas",
    "jurisway",
    "lfg",
    "mj",
    "mp-am",
    "mp-df",
    "mp-pb",
    "mp-pr",
    "mp-rs",
    "mpf",
    "mps",
    "mpt-prt4",
    "mpt-prt5",
    "msn",
    "oab",
    "oab-ba",
    "oab-ce",
    "oab-df",
    "oab-ma",
    "oab-ms",
    "oab-pe",
    "oab-rn",
    "oab-rs",
    "oab-sc",
    "oab-se",
    "oab-sp",
    "oab-to",
    "observatorio-eco",
    "pgr",
    "pndt",
    "portal-justificando",
    "pr-rs",
    "r7",
    "rf",
    "sebrae-sp",
    "senado",
    "sindjufe-go",
    "stj",
    "tce-ba",
    "tce-ce",
    "tce-ma",
    "tce-sc",
    "tce-se",
    "tcu",
    "tj-ce",
    "tj-df",
    "tj-es",
    "tj-go",
    "tj-mg",
    "tj-ms",
    "tj-pr",
    "tj-sc",
    "tre-ac",
    "tre-al",
    "tre-ap",
    "tre-ce",
    "tre-df",
    "tre-es",
    "tre-go",
    "tre-ma",
    "tre-mg",
    "tre-ms",
    "tre-mt",
    "tre-pa",
    "tre-pb",
    "tre-pi",
    "tre-pr",
    "tre-rj",
    "tre-rn",
    "tre-ro",
    "tre-rr",
    "tre-rs",
    "tre-sc",
    "tre-se",
    "tre-sp",
    "tre-to",
    "trf-1",
    "trf-4",
    "trf-5",
    "trt-13",
    "trt-14",
    "trt-15",
    "trt-2",
    "trt-20",
    "trt-6",
    "trt-7",
    "tse",
    "tst",
    "ultima-instancia",
    "unafe",
    "uol",
    "yahoo",
    "bndes",
    "dp-ms",
    "oab-mg",
    "coad",
    "anda",
    "amb",
    "al-ma",
    "iape",
    "al-am",
    "amagis",
    "carta-forense",
    "csjt",
    "direito-domestico",
    "direito-legal",
    "fenasj",
    "folha",
    "iab",
    "iaf",
    "stm",
    "tce-rs",
    "trf-2",
    "olhar-digital",
    "tech-tudo",
    "computer-world",
    "sbt",
    "estadao",
    "veja",
    "exame",
    "gazeta-do-povo",
    "epoca",
    "imaster",
    "abrampa",
    "terra",
    "dp-pe",
    "sintese",
    "tce-ms",
    "dias-brasil-adv",
    "trt-10",

    # # Failing Tests
    "stf",
    "tj-rj",
    "trt-3",
    "sefaz-to",
    "aasp",
    "anpt",
    "trt-4",
    "direito-do-estado",  # <<<<<<<
    "enm",  # <<<<<<<
    "abojeris",
    "acat",
    "dp-sp",
    "mp-mt",
    "mpt",
    "oab-al",
    "oab-es",
    "oab-go",
    "oab-mt",
    "sefaz-rs",
    "sefaz-sc",
    "sefaz-sp",
    "tj-sp",
    "trf-3",
    "trt-24",
])
def test_title_extractor(website):
    url_file_path = "tests/resources/pt/{}/url.txt".format(website)
    title_file_path = "tests/resources/pt/{}/title.txt".format(website)
    html_file_path = "tests/resources/pt/{}/page.html".format(website)

    url = _get_contents_of(url_file_path)
    html = _get_contents_of(html_file_path)

    expected_title = _get_contents_of(title_file_path)

    ferret = Ferret(url, html)
    assert expected_title == ferret.extract_title()
