import pytest
from ferret.main import Ferret


def _get_contents_of(file_path):
    try:
        with open(file_path, errors='ignore') as file:
            return file.read()
    except IOError:
        return None


@pytest.mark.parametrize("language,website", [
    ("pt", "aasp"),
    ("pt", "aba"),
    ("pt", "abdc"),
    ("pt", "age-mg"),
    ("pt", "agencia-brasil"),
    ("pt", "agu"),
    ("pt", "ajufe"),
    ("pt", "ajufergs"),
    ("pt", "al-ac"),
    ("pt", "al-ce"),
    ("pt", "al-go"),
    ("pt", "al-ms"),
    ("pt", "al-mt"),
    ("pt", "al-pb"),
    ("pt", "al-rj"),
    ("pt", "al-rs"),
    ("pt", "al-sp"),
    ("pt", "al-to"),
    ("pt", "amab"),
    ("pt", "amatra-05"),
    ("pt", "ambito-juridico"),
    ("pt", "anamatra"),
    ("pt", "anpt"),
    ("pt", "apbc"),
    ("pt", "apeminas"),
    ("pt", "cd"),
    ("pt", "cgu"),
    ("pt", "cnj"),
    ("pt", "cnmp"),
    ("pt", "conamp"),
    ("pt", "consultor-juridico"),
    ("pt", "controle-publico"),
    ("pt", "correio-forense"),
    ("pt", "correio_da_bahia"),
    ("pt", "dp-al"),
    ("pt", "dp-df"),
    ("pt", "dp-mg"),
    ("pt", "dp-mt"),
    ("pt", "dp-rj"),
    ("pt", "dp-rs"),
    ("pt", "dp-to"),
    ("pt", "dpu"),
    ("pt", "folhapolitica"),
    ("pt", "g1"),
    ("pt", "ibdfam"),
    ("pt", "ibdp-direito-previdenciario"),
    ("pt", "inst-rui-barbosa"),
    ("pt", "internet-legal"),
    ("pt", "jf"),
    ("pt", "jf-al"),
    ("pt", "jornal-ordem-rs"),
    ("pt", "juristas"),
    ("pt", "jurisway"),
    ("pt", "lfg"),
    ("pt", "mj"),
    ("pt", "mp-am"),
    ("pt", "mp-df"),
    ("pt", "mp-pb"),
    ("pt", "mp-pr"),
    ("pt", "mp-rs"),
    ("pt", "mpf"),
    ("pt", "mps"),
    ("pt", "mpt-prt4"),
    ("pt", "mpt-prt5"),
    ("pt", "msn"),
    ("pt", "oab"),
    ("pt", "oab-ba"),
    ("pt", "oab-ce"),
    ("pt", "oab-df"),
    ("pt", "oab-ma"),
    ("pt", "oab-ms"),
    ("pt", "oab-pe"),
    ("pt", "oab-rn"),
    ("pt", "oab-rs"),
    ("pt", "oab-sc"),
    ("pt", "oab-se"),
    ("pt", "oab-sp"),
    ("pt", "oab-to"),
    ("pt", "observatorio-eco"),
    ("pt", "pgr"),
    ("pt", "pndt"),
    ("pt", "portal-justificando"),
    ("pt", "pr-rs"),
    ("pt", "r7"),
    ("pt", "rf"),
    ("pt", "sebrae-sp"),
    ("pt", "senado"),
    ("pt", "sindjufe-go"),
    ("pt", "stj"),
    ("pt", "tce-ba"),
    ("pt", "tce-ce"),
    ("pt", "tce-ma"),
    ("pt", "tce-sc"),
    ("pt", "tce-se"),
    ("pt", "tcu"),
    ("pt", "tj-ce"),
    ("pt", "tj-df"),
    ("pt", "tj-es"),
    ("pt", "tj-go"),
    ("pt", "tj-mg"),
    ("pt", "tj-ms"),
    ("pt", "tj-pr"),
    ("pt", "tj-sc"),
    ("pt", "tre-ac"),
    ("pt", "tre-al"),
    ("pt", "tre-ap"),
    ("pt", "tre-ce"),
    ("pt", "tre-df"),
    ("pt", "tre-es"),
    ("pt", "tre-go"),
    ("pt", "tre-ma"),
    ("pt", "tre-mg"),
    ("pt", "tre-ms"),
    ("pt", "tre-mt"),
    ("pt", "tre-pa"),
    ("pt", "tre-pb"),
    ("pt", "tre-pi"),
    ("pt", "tre-pr"),
    ("pt", "tre-rj"),
    ("pt", "tre-rn"),
    ("pt", "tre-ro"),
    ("pt", "tre-rr"),
    ("pt", "tre-rs"),
    ("pt", "tre-sc"),
    ("pt", "tre-se"),
    ("pt", "tre-sp"),
    ("pt", "tre-to"),
    ("pt", "trf-1"),
    ("pt", "trf-4"),
    ("pt", "trf-5"),
    ("pt", "trt-13"),
    ("pt", "trt-14"),
    ("pt", "trt-15"),
    ("pt", "trt-2"),
    ("pt", "trt-20"),
    ("pt", "trt-6"),
    ("pt", "trt-7"),
    ("pt", "tse"),
    ("pt", "tst"),
    ("pt", "ultima-instancia"),
    ("pt", "unafe"),
    ("pt", "uol"),
    ("pt", "yahoo"),
    ("pt", "bndes"),
    ("pt", "dp-ms"),
    ("pt", "oab-mg"),
    ("pt", "sintese"),
    ("pt", "tce-ms"),
    ("pt", "coad"),
    ("pt", "anda"),
    ("pt", "amb"),
    ("pt", "al-ma"),
    ("pt", "iape"),
    ("pt", "al-am"),
    ("pt", "sefaz-to"),
    ("pt", "amagis"),
    ("pt", "carta-forense"),
    ("pt", "csjt"),
    ("pt", "direito-domestico"),
    ("pt", "direito-legal"),
    ("pt", "espaco-vital"),
    ("pt", "fenasj"),
    ("pt", "folha"),
    ("pt", "iab"),
    ("pt", "iaf"),
    ("pt", "stm"),
    ("pt", "tce-rs"),
    ("pt", "trf-2"),
    ("pt", "olhar-digital"),
    ("pt", "tech-tudo"),
    ("pt", "computer-world"),
    ("pt", "sbt"),
    ("pt", "estadao"),
    ("pt", "veja"),
    ("pt", "exame"),
    ("pt", "gazeta-do-povo"),
    ("pt", "epoca"),
    ("pt", "imaster"),
    ("pt", "dp-pe"),
    ("pt", "abrampa"),
    ("pt", "terra"),

    # Failing Tests
    # ("pt", "direito-do-estado"),  # <<<<<<<
    # ("pt", "enm"),  # <<<<<<<
    # ("pt", "abojeris"),
    # ("pt", "acat"),
    # ("pt", "dias-brasil-adv"),
    # ("pt", "dp-sp"),
    # ("pt", "mp-mt"),
    # ("pt", "mpt"),
    # ("pt", "oab-al"),
    # ("pt", "oab-es"),
    # ("pt", "oab-go"),
    # ("pt", "oab-mt"),
    # ("pt", "sefaz-rs"),
    # ("pt", "sefaz-sc"),
    # ("pt", "sefaz-sp"),
    # ("pt", "stf"),
    # ("pt", "tj-rj"),
    # ("pt", "tj-sp"),
    # ("pt", "trf-3"),
    # ("pt", "trt-10"),
    # ("pt", "trt-24"),
    # ("pt", "trt-3"),
    # ("pt", "trt-4"),
])
def test_title_extractor(language, website):
    url_file_path = "tests/resources/{}/{}/url.txt".format(language, website)
    title_file_path = "tests/resources/{}/{}/title.txt".format(language, website)
    html_file_path = "tests/resources/{}/{}/page.html".format(language, website)

    url = _get_contents_of(url_file_path)
    html = _get_contents_of(html_file_path)

    expected_title = _get_contents_of(title_file_path)

    ferret = Ferret(url, html)
    assert expected_title == ferret.extract_title()


@pytest.mark.parametrize("language,website", [
    ("pt", "agencia-brasil"),
    ("pt", "agu"),
    ("pt", "ajufergs"),
    ("pt", "al-sp"),
    ("pt", "al-to"),
    ("pt", "cd"),
    ("pt", "cgu"),
    ("pt", "cnj"),
    ("pt", "consultor-juridico"),
    ("pt", "dp-al"),
    ("pt", "dp-df"),
    ("pt", "dp-mg"),
    ("pt", "dp-rs"),
    ("pt", "dp-to"),
    ("pt", "g1"),
    ("pt", "ibdfam"),
    ("pt", "ibdp-direito-previdenciario"),
    ("pt", "jf"),
    ("pt", "jurisway"),
    ("pt", "mp-pr"),
    ("pt", "mp-rs"),
    ("pt", "mps"),
    ("pt", "oab-ba"),
    ("pt", "oab-ma"),
    ("pt", "oab-pe"),
    ("pt", "oab-se"),
    ("pt", "oab-sp"),
    ("pt", "oab-to"),
    ("pt", "pndt"),
    ("pt", "portal-justificando"),
    ("pt", "rf"),
    ("pt", "senado"),
    ("pt", "tce-sc"),
    ("pt", "tce-se"),
    ("pt", "tj-ms"),
    ("pt", "tj-sc"),
    ("pt", "tre-ap"),
    ("pt", "tre-ce"),
    ("pt", "tre-df"),
    ("pt", "tre-es"),
    ("pt", "tre-go"),
    ("pt", "tre-ma"),
    ("pt", "tre-ms"),
    ("pt", "tre-mt"),
    ("pt", "tre-pa"),
    ("pt", "tre-pb"),
    ("pt", "tre-pi"),
    ("pt", "tre-rn"),
    ("pt", "tre-ro"),
    ("pt", "tre-se"),
    ("pt", "tre-sp"),
    ("pt", "tre-to"),
    ("pt", "trt-6"),
    ("pt", "tse"),
    ("pt", "ultima-instancia"),
    ("pt", "unafe"),
    ("pt", "uol"),
    ("pt", "bndes"),
    ("pt", "tce-ms"),
    ("pt", "coad"),
    ("pt", "anda"),
    ("pt", "al-ma"),
    ("pt", "iape"),
    ("pt", "amagis"),
    ("pt", "direito-domestico"),
    ("pt", "direito-legal"),
    ("pt", "espaco-vital"),
    ("pt", "fenasj"),
    ("pt", "iaf"),
    ("pt", "trf-2"),
    ("pt", "tech-tudo"),
    ("pt", "sbt"),
    ("pt", "exame"),
    ("pt", "gazeta-do-povo"),
    ("pt", "epoca"),
    ("pt", "imaster"),
    ("pt", "direito-do-estado"),
    ("pt", "dias-brasil-adv"),
    ("pt", "oab-es"),
    ("pt", "oab-go"),
    ("pt", "sefaz-sc"),
    ("pt", "sefaz-sp"),
    ("pt", "tj-rj"),
    ("pt", "trt-10"),
    ("pt", "trt-3"),
    ("pt", "computer-world"),
    ("pt", "jornal-ordem-rs"),
    ("pt", "oab-df"),
    ("pt", "tj-ce"),
    ("pt", "trt-13"),
    ("pt", "sefaz-to"),
    ("pt", "veja"),
    ("pt", "enm"),
    ("pt", "trt-24"),
    ("pt", "al-ac"),
    ("pt", "amatra-05"),
    ("pt", "apeminas"),
    ("pt", "dp-rj"),
    ("pt", "folhapolitica"),
    ("pt", "internet-legal"),
    ("pt", "juristas"),
    ("pt", "lfg"),
    ("pt", "oab"),
    ("pt", "oab-sc"),
    ("pt", "tre-mg"),
    ("pt", "tre-pr"),
    ("pt", "tre-rr"),
    ("pt", "stf"),
    ("pt", "al-ce"),
    ("pt", "al-mt"),
    ("pt", "al-pb"),
    ("pt", "al-rj"),
    ("pt", "amab"),
    ("pt", "anamatra"),
    ("pt", "apbc"),
    ("pt", "cnmp"),
    ("pt", "controle-publico"),
    ("pt", "jf-al"),
    ("pt", "mp-am"),
    ("pt", "mp-df"),
    ("pt", "mpf"),
    ("pt", "mpt-prt4"),
    ("pt", "mpt-prt5"),
    ("pt", "oab-ce"),
    ("pt", "oab-ms"),
    ("pt", "pgr"),
    ("pt", "pr-rs"),
    ("pt", "sebrae-sp"),
    ("pt", "sindjufe-go"),
    ("pt", "tj-es"),
    ("pt", "tre-ac"),
    ("pt", "tre-al"),
    ("pt", "trf-1"),
    ("pt", "trt-2"),
    ("pt", "yahoo"),
    ("pt", "dp-ms"),
    ("pt", "trt-20"),
    ("pt", "trt-7"),
    ("pt", "sintese"),
    ("pt", "folha"),
    ("pt", "estadao"),
    ("pt", "amb"),
    ("pt", "abojeris"),
    ("pt", "oab-al"),
    ("pt", "csjt"),
    ("pt", "tj-go"),
    ("pt", "tre-rj"),
    ("pt", "tre-rs"),
    ("pt", "trf-4"),
    ("pt", "stm"),
    ("pt", "trt-4"),
    ("pt", "aba"),
    ("pt", "dpu"),
    ("pt", "tce-rs"),
    ("pt", "oab-mg"),
    ("pt", "carta-forense"),
    ("pt", "oab-mt"),
    ("pt", "tj-sp"),
    ("pt", "al-ms"),
    ("pt", "al-rs"),
    ("pt", "conamp"),
    ("pt", "mp-pb"),
    ("pt", "oab-rs"),
    ("pt", "tce-ce"),
    ("pt", "tj-mg"),
    ("pt", "tj-pr"),
    ("pt", "tj-df"),
    ("pt", "dp-sp"),
    ("pt", "iab"),
    ("pt", "sefaz-rs"),
    ("pt", "ambito-juridico"),

    # ("pt", "trf-3"),
    # ("pt", "tcu"),
    # ("pt", "tre-sc"),
    # ("pt", "mp-mt"),
    # ("pt", "ajufe"),
    # ("pt", "trf-5"),
    # ("pt", "stj"),
    # ("pt", "abrampa"),
    # ("pt", "al-am"),
    # ("pt", "correio-forense"),
    # ("pt", "olhar-digital"),
    # ("pt", "anpt"),
    # ("pt", "correio_da_bahia"),
    # ("pt", "dp-mt"),
    # ("pt", "inst-rui-barbosa"),
    # ("pt", "mj"),
    # ("pt", "msn"),
    # ("pt", "oab-rn"),
    # ("pt", "observatorio-eco"),
    # ("pt", "r7"),
    # ("pt", "tce-ba"),
    # ("pt", "tce-ma"),
    # ("pt", "terra"),
    # ("pt", "trt-14"),
    # ("pt", "trt-15"),
    # ("pt", "tst"),
    # ("pt", "mpt"), # Existe uma outra data próxima. Solução: proximidade do título.
    # ("pt", "acat"), # Não tem no texto
    # ("pt", "al-go"),

    # There is no date in the HTML page
    # ("pt", "dp-pe"),
    # ("pt", "age-mg"),
])
def test_published_date_extraction(language, website):
    url_file_path = "tests/resources/{}/{}/url.txt".format(language, website)
    date_file_path = "tests/resources/{}/{}/date.txt".format(language, website)
    html_file_path = "tests/resources/{}/{}/page.html".format(language, website)

    url = _get_contents_of(url_file_path)
    html = _get_contents_of(html_file_path)

    expected_date = _get_contents_of(date_file_path)

    ferret = Ferret(url, html)
    article = ferret.get_article()
    extracted_date = article['published_date']
    assert expected_date[:10] == extracted_date[:10]
